apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: python-server
  name: python-server
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: python-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-server
    spec:
      containers:
      - image: public.ecr.aws/u9r8b2p6/python-server:0.0.3
        imagePullPolicy: Always
        env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: python-server
                key: message
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 31
        name: python-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: python-server
  name: python-server
spec:
  clusterIP: 172.20.153.174
  clusterIPs:
  - 172.20.153.174
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: python-server
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: python-server
data:
  message: Visit yourdevopsmentor.com for more challanges!
